apiVersion: v1
kind: Service
metadata:
  name: shipping-service
  labels:
    app: ecommerce
spec:
  selector:
    app: ecommerce
    tier: shipping
  ports:
  - port: 3001
    targetPort: 3001
  type: NodePort
