apiVersion: v1
kind: Service
metadata:
  name: order-service
  labels:
    app: ecommerce
spec:
  selector:
    app: ecommerce
    tier: order
  ports:
  - port: 3000
    targetPort: 3000
  type: NodePort
